name: Render resume
on:
  push:
    branches:
    - main
    paths:
    - '/HenryArendResume.md'

jobs:
  ConvertToPDF:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: pdfs