name: Render Markdown to PDF and Create Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: cornelius/action-md-as-pdf@main
        if: github.ref == 'refs/heads/main'
        with:
          markdown_dir: docs
          pdf_file: output.pdf
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: Generated PDF
          path: output.pdf
