name: Render Markdown to PDF and Create Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create PDF
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: docs/HenryArendResume.md
          output_dir: pdfs
          build_pdf: true
          theme: docs/resume.css
      - name: Publish PDF
        run: |
          gh release upload ${{ github.sha }} pdfs/HenryArendResume.pdf
